services:
#    pff_user.example:
#        class: PFF\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     pff_user.registration_listener:
         class: PFF\UserBundle\Listener\RegistrationListener
         tags:
            - { name: kernel.event_listener, event: fos_user.registration.completed, method: onKernelResponse, priority: 255 }