<?php

namespace PFF\BourseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BeneficiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiaireRepository extends EntityRepository
{
    public function dernierIdBene(){
        $query=$this->createQueryBuilder('b')
            ->orderBy('b.id','DESC')
            ->setMaxResults(1)
            ->getQuery();
        return $query->getResult();
    }
	public function matricule(){
		$query=$this->createQueryBuilder('b')
			->select('b.numMlle')
			->getQuery();
			return $query->getResult();

    }
    public function beneficiaire($id){
        $query=$this->createQueryBuilder('ben')
            ->select('bene')
            ->where('ben.id=:i')
            ->setParameter('a',$id)
            ->getQuery();
        return $query->getResult();

    }
    public function reqiug(){
        return $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.faculte = :a')
            ->setParameter('a','1')
            ->getQuery()
            ->getSingleResult();
    }
    public function reqfst(){
        return $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.faculte = :a')
            ->setParameter('a','2')
            ->getQuery()
            ->getSingleResult();
    }
    public function reqfhg(){
        return $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.faculte = :a')
            ->setParameter('a','4')
            ->getQuery()
            ->getSingleResult();
    }
    public function reqfseg(){
        return $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.faculte = :a')
            ->setParameter('a','3')
            ->getQuery()
            ->getSingleResult();
    }
    public function reqfdpri(){
        return $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.faculte = :a')
            ->setParameter('a','5')
            ->getQuery()
            ->getSingleResult();
    }
    public function reqfdpu(){
        return $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.faculte = :a')
            ->setParameter('a','6')
            ->getQuery()
            ->getSingleResult();
    }
    public function reqfmp(){
        return $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.faculte = :a')
            ->setParameter('a','5')
            ->getQuery()
            ->getSingleResult();
    }
    public function reqfmpos(){
        return $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.faculte = :a')
            ->setParameter('a','5')
            ->getQuery()
            ->getSingleResult();
    }

    public function nb2017(){
        return $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.	anenr = :a')
            ->setParameter('a','2017')
            ->getQuery()
            ->getSingleResult();
    }

    public function nb2016(){
        return $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.	anenr = :a')
            ->setParameter('a','2016')
            ->getQuery()
            ->getSingleResult();
    }
    public function nb2015(){
        return $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.	anenr = :a')
            ->setParameter('a','2015')
            ->getQuery()
            ->getSingleResult();
    }
}
