<?php

namespace PFF\BourseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FaculteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaculteRepository extends EntityRepository
{
}
