<?php

namespace PFF\BourseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FondsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FondsRepository extends EntityRepository
{
}
