<?php

namespace PFF\BourseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{
    public function bFormation(){
        $query=$this->createQueryBuilder('b')
            ->leftJoin('b.Beneficiaire','f')
            ->addSelect('f')
            ->getQuery();
        return $query->getResult();
    }
}
