<?php

namespace PFF\BourseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueRepository extends EntityRepository
{

    public function bFondsHist ($id){
        $query=$this->createQueryBuilder('b')
            ->leftJoin('b.beneficiaire','f')
            ->where('f.id = :R')
            ->setParameter('R',$id)
            ->getQuery();
        return $query->getResult();
    }
}
