<?php

namespace Proxies\__CG__\PFF\BourseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Beneficiaire extends \PFF\BourseBundle\Entity\Beneficiaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'id', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'historiques', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'faculte', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'numMlle', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'nom', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'prenom', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'dateNais', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'adresse', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'numTel', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'sexe', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'email', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'niveau', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'statut', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'anenr'];
        }

        return ['__isInitialized__', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'id', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'historiques', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'faculte', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'numMlle', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'nom', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'prenom', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'dateNais', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'adresse', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'numTel', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'sexe', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'email', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'niveau', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'statut', '' . "\0" . 'PFF\\BourseBundle\\Entity\\Beneficiaire' . "\0" . 'anenr'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Beneficiaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumMlle($numMlle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumMlle', [$numMlle]);

        return parent::setNumMlle($numMlle);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumMlle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumMlle', []);

        return parent::getNumMlle();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNais($dateNais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNais', [$dateNais]);

        return parent::setDateNais($dateNais);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNais', []);

        return parent::getDateNais();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumTel($numTel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumTel', [$numTel]);

        return parent::setNumTel($numTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumTel', []);

        return parent::getNumTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau($niveau)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setFaculte(\PFF\BourseBundle\Entity\Faculte $faculte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFaculte', [$faculte]);

        return parent::setFaculte($faculte);
    }

    /**
     * {@inheritDoc}
     */
    public function getFaculte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFaculte', []);

        return parent::getFaculte();
    }

    /**
     * {@inheritDoc}
     */
    public function addHistorique(\PFF\BourseBundle\Entity\Historique $historique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHistorique', [$historique]);

        return parent::addHistorique($historique);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHistorique(\PFF\BourseBundle\Entity\Historique $historique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHistorique', [$historique]);

        return parent::removeHistorique($historique);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoriques()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoriques', []);

        return parent::getHistoriques();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnenr($anenr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnenr', [$anenr]);

        return parent::setAnenr($anenr);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnenr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnenr', []);

        return parent::getAnenr();
    }

}
